name: Release build

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      STACK_ROOT: /root/.stack

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          stack-version: '2.7.3'

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: ${{ env.STACK_ROOT }}
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: |
          stack setup --allow-different-user
          stack --local-bin-path . install --allow-different-user
          mv ./glados-exe ./glados

      - name: Install zip
        run: |
          sudo apt-get install zip -y
          sudo apt-get install tar -y

      - name: Zip source files
        run: |
          zip -r glados-sources.zip app src test package.yaml stack.yaml README.md
          tar -czvf glados-sources.tar.gz app src test package.yaml stack.yaml README.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            glados
            glados-sources.zip
            glados-sources.tar.gz
          tag_name: ${{ github.ref }}
          body: |
            ${{ github.event.release.body }}
          draft: false
          prerelease: false
