name: Release build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.7'
          stack-version: '2.7.3'

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Linux Build
        run: |
          stack --local-bin-path . install --system-ghc
          mv ./glados-exe ./glados
          chmod +x ./glados

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            glados
