name: Unit testing

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: haskell:8.10.4
    env:
      STACK_ROOT: /root/.stack


    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          stack setup
          stack build --allow-different-user

      - name: Test
        run: stack test --coverage
