name: Unit testing

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: haskell:8.10.4
    env:
      STACK_ROOT: /root/.stack


    steps:
      - uses: actions/checkout@v3

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: ${{ env.STACK_ROOT }}
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: |
          stack setup --allow-different-user
          stack build --allow-different-user

      - name: Test
        run: stack test --coverage --allow-different-user
