name: Unit testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.4.7'
          stack-version: '2.11.1'

      - name: Build
        run: stack build

      - name: Test
        run: stack test --coverage
