name: Unit testing

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: haskell:latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: stack build

      - name: Test
        run: stack test --coverage
