name: Unit testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.4.7'
          stack-version: '2.7.3'

      - name: Cache stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: |
          stack setup --allow-different-user
          stack build --allow-different-user

      - name: Test
        run: stack test --coverage --allow-different-user
